swagger: "2.0"
info:
  description: "Key Phrases Extraction using 'CoreNLP' Python modules."
  version: "0.1.0"
  title: "Key Phrases Extraction Demo"
  contact:
    email: "omar@veriguide.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.1.29"
basePath: "/kpapi/v1"
tags:
- name: "Submit"
  description: "Submit document to extract key phrases"
- name: "Query"
  description: "To query the result of extraction"
- name: "Internal Call"
  description: "Used internally"
schemes:
- "http"
- "https"
paths:
  /essay:
    post:
      tags:
        - "Submit"
      summary: "Submit the document"
      description: ""
      operationId: "submitDoc"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
      - name: "essay"
        in: "query"
        description: "Documents to be extracted"
        required: true
        type: "string"
      - name: "title"
        in: "query"
        description: "Title of the Document"
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultMsg"
        502:
          description: "database error"
          schema:
            $ref: "#/definitions/SystemMsg"
  /result:
    get:
      tags:
      - "Query"
      summary: "Returns key phrases by hash value"
      description: ""
      operationId: "result"
      produces:
        - "application/json"
      parameters:
      - name: "hash_val"
        in: "query"
        description: "UUIDv4"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultMsg"
        502:
          description: "database error"
          schema:
            $ref: "#/definitions/SystemMsg"
  /selectall:
    get:
      tags:
      - "Query"
      summary: "Get all previous result of extraction"
      description: ""
      operationId: "selectall"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "query"
        description: "UUIDv4"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              obj:
                type: "array"
                items:
                  $ref: "#/definitions/ResultMsg"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
  /selectfail:
    get:
      tags:
      - "Query"
      summary: "Get all records cannot be extracted key phrases"
      description: ""
      operationId: "selectfail"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "query"
        description: "UUIDv4"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              obj:
                type: "array"
                items:
                  $ref: "#/definitions/ResultMsg"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
  /upload:
    post:
      tags:
      - "Query"
      summary: "Upload text file to extract key phrase"
      description: ""
      operationId: "upload"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Text file contains document"
        required: true
        type: "file"
      responses:
        201:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "OK"
              msg:
                type: "string"
              hash:
                type: "string"
        200:
          description: "already exist"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "OK"
              obj:
                type: "array"
                items:
                  $ref: "#/definitions/ResultMsg"
        404:
          description: "POST method is preferred"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
  /updatekpdb:
    post:
      tags:
      - "Internal Call"
      summary: "Write key phrases to database"
      description: ""
      operationId: "updatekpdb"
      responses:
        200:
          description: "success operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              obj:
                type: "array"
                items:
                  type: "object"
                  properties:
                    hash:
                      type: "string"
                    kp:
                      type: "string"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
  /kpextract:
    post:
      tags:
      - "Internal Call"
      summary: "Process key phrases extraction using CoreNLP"
      description: "This does batch process from working pool(Redis)"
      operationId: "kpextract"
      responses:
        200:
          description: "success operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              obj:
                type: "string"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"
  /doalljob:
    post:
      tags:
      - "Internal Call"
      summary: "Trigger process all pending jobs"
      description: ""
      operationId: "doalljob"
      responses:
        200:
          description: "success operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              poolsize:
                type: "number"
                format: "i32"
                example: 9
              pool:
                type: "string"
        502:
          description: "query one failed"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "FAILED"
              msg:
                type: "string"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  ResultMsg:
    type: "object"
    properties:
      status:
        type: "string"
      msg:
        type: "string"
      hash:
        type: "string"
      title:
        type: "string"
      content:
        type: "string"
      kp:
        type: "string"
      model:
        type: "string"
      date:
        type: "string"
  SystemMsg:
    type: "object"
    properties:
      status:
        type: "string"
      msg:
        type: "string"
      hash:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
